{
 "title": "OTRS - Enquete",
 "tags": [ "otrs" ],
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "questao",
    "label": "Questão",
    "query": "SELECT question FROM survey_question sq JOIN survey s ON (s.id=sq.survey_id AND s.status='Master')"
   }
  ]
 },
 "panels": [
  {
   "title": "Chamados fechados",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \nUNIX_TIMESTAMP(th.create_time) as time_sec,\ncount(*) as value,\ntst.name as metric\nFROM ticket_history th\nJOIN ticket t ON (th.ticket_id=t.id)\nJOIN users u ON (th.owner_id=u.id)\nJOIN ticket_state ts ON (th.state_id=ts.id)\nJOIN ticket_state_type tst ON (ts.type_id=tst.id)\nWHERE\ntst.name = 'closed'\nAND th.history_type_id = 27\nAND $__timeFilter(th.create_time)\nGROUP BY th.create_time, tst.name"
    }
   ]
  },
  {
   "title": "Solicitações enviadas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \nUNIX_TIMESTAMP(survey_request.create_time) as time_sec,\ncount(survey_request.id) as value,\n'chamados' as metric\nFROM survey_request\nWHERE\n$__timeFilter(survey_request.create_time)\nGROUP BY survey_request.create_time, survey_request.id\n"
    }
   ]
  },
  {
   "title": "Solicitações respondidas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \nUNIX_TIMESTAMP(survey_request.vote_time) as time_sec,\ncount(survey_request.id) as value,\n'chamados' as metric\nFROM survey_request\nWHERE\nvote_time IS NOT NULL\nAND\n$__timeFilter(survey_request.vote_time)\nGROPU BY survey_request.vote_time, survey_request.id\n"
    }
   ]
  },
  {
   "title": "Respostas",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n$__timeGroup(survey_request.vote_time,'24h') as time_sec,\ncount(survey_request.id) as value,\n'Respostas' as metric\nFROM survey_request\nWHERE\nvote_time IS NOT NULL\nAND\n$__timeFilter(survey_request.vote_time)\nGROUP BY vote_value, sv.create_time, sa.answer\nORDER BY 1\n\n"
    }
   ]
  },
  { "title": "$questao", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "questao" },
  {
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(sv.create_time) as time_sec,\n  count(vote_value) as value,\n  CASE sq.question_type\n    WHEN 'Radio'\n    THEN sa.answer \n    WHEN 'Textarea'\n    THEN REPLACE(sv.vote_value,'$html/text$','')\n    ELSE sv.vote_value\n  END as metric\nFROM survey_vote sv\nLEFT JOIN survey_answer sa ON (sv.vote_value=sa.id)\nJOIN survey_question sq ON (sq.id=sv.question_id)\nWHERE\n$__timeFilter(sv.create_time)\nAND sq.question = $questao\nGROUP BY vote_value\nORDER BY sa.position\n"
    }
   ]
  },
  {
   "title": "Chamados avaliados",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  t.tn,\n  t.title,\n  q.name,\n  CASE sq.question_type\n    WHEN 'Radio'\n    THEN sa.answer \n    WHEN 'Textarea'\n    THEN REPLACE(sv.vote_value,'$html/text$','')\n    ELSE sv.vote_value\n  END as answer\nFROM survey_vote sv\nLEFT JOIN survey_answer sa ON (sv.vote_value=sa.id)\nJOIN survey_question sq ON (sq.id=sv.question_id)\nJOIN survey_request sr ON (sv.request_id=sr.id)\nJOIN ticket t ON (t.id=sr.ticket_id)\nJOIN queue q ON (t.queue_id=q.id)\nWHERE\n$__timeFilter(sv.create_time)\nAND\nsq.question IN ($questao)\nORDER BY sa.position, t.tn DESC"
    }
   ]
  }
 ]
}